<?php
// Automatically Generated by TestLink Installer - Wed, 28 Sep 16 14:59:03 +0800
define('DB_TYPE', 'mysql');
define('DB_USER', 'testlink');
define('DB_PASS', '123456');
define('DB_HOST', 'localhost');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
